on:
  push:
    branches:    
      - main

jobs:
  build:
   runs-on: ubuntu-22.04
   name: Artifact build
   steps:
    - uses: actions/checkout@v3
    - name: Detach HEAD
      run: |
         git checkout --detach 
         echo "--------------------------------------------"
         git status
         echo "--------------------------------------------"
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Install ncc 
      run: |
        cd node
        npm i -g @vercel/ncc
    - name: Compile 
      run: |
        cd node
        ncc build index.js --license licenses.txt
    - name: Create commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "--------------------------------------------"
        git rm -r --force *
        echo "--------------------------------------------"
        git add --force README.md
        git add --force LICENSE
        git add --force action.yml
        git add --force node/dist/index.js
        echo "--------------------------------------------"
        git commit --message="Action release"
        echo "--------------------------------------------"
        git tag --annotate --message="Action release" v1
        echo "--------------------------------------------"
        git status
        echo "--------------------------------------------"
        git log -3 --oneline
        echo "--------------------------------------------"
        git push origin v1