on:
  push:
    branches:    
      - main

jobs:
  build:
   runs-on: ubuntu-22.04
   name: Artifact build
   steps:
    - uses: actions/checkout@v3
    - name: Detach HEAD
      run: |
         git checkout --detach 
         git status
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Install ncc 
      run: |
        cd node
        npm i -g @vercel/ncc

