on:
  push:
    branches:    
      - main

jobs:
  build:
   runs-on: ubuntu-22.04
   name: Artifact build
   steps:
    - uses: actions/checkout@v3
    - name: Detach HEAD
      run: |
         git checkout --detach 
         git status
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Install ncc 
      run: |
        cd node
        npm i -g @vercel/ncc
    - name: Compile 
      run: |
        cd node
        ncc build index.js --license licenses.txt
    - name: create commit
      run: |
        git add --force action.yml
        git add --force node/dist/index.js
        git commit --message="Action release"
        git tag --annotate --message="Action release" v1
        git push --follow-tags