on:
  push:
    branches:    
      - main

env:
  RELEASE_VERSION: v1

jobs:
  build:
   runs-on: ubuntu-22.04
   name: Artifact build
   steps:
    - uses: actions/checkout@v3
    - name: Detach HEAD
      run: |
         git checkout --detach 
         echo "--------------------------------------------"
         git status
         echo "--------------------------------------------"
    - name: Install dependencies
      run: |
        cd node
        npm install
    - name: Install ncc 
      run: |
        cd node
        npm i -g @vercel/ncc
    - name: Compile 
      run: |
        cd node
        ncc build index.js --license licenses.txt
    - name: Create commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "--------------------------------------------"
        git rm -r --force '*'
        echo "--------------------------------------------"
        git reset -- README.md
        git restore -- README.md
        git reset -- LICENSE
        git restore -- LICENSE
        git reset -- action.yml
        git restore -- action.yml
        echo "--------------------------------------------"
        git add --force node/dist/index.js
        echo "--------------------------------------------"
        git commit --message="Action release"
        echo "--------------------------------------------"
        git push origin :refs/tags/${{ env.RELEASE_VERSION }}
        echo "--------------------------------------------"
        git tag --force --annotate --message="Action release" ${{ env.RELEASE_VERSION }}
        echo "--------------------------------------------"
        git status
        echo "--------------------------------------------"
        git log -3 --oneline
        echo "--------------------------------------------"
        git push origin ${{ env.RELEASE_VERSION }}